;;; auto-header-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from auto-header.el

(autoload 'auto-header-at-point "auto-header" "\
Insert headers for NAME.
When called interactively, use the symbol at or before point as
NAME.

(fn NAME)" t)
(autoload 'auto-header-buffer "auto-header" "\
Insert the headers for all functions." t)
(autoload 'auto-header-mode "auto-header" "\
Run `auto-header-buffer' before saving.

This is a minor mode.  If called interactively, toggle the
`Auto-Header mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `auto-header-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "auto-header" '("auto-header-"))

;;; End of scraped data

(provide 'auto-header-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; auto-header-autoloads.el ends here
