import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
   "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 10.0

[font.bold]
family = "GoMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "GoMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "GoMono Nerd Font"
style = "Italic"

[font.normal]
family = "GoMono Nerd Font"
style = "Regular"